/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CommandDefinitionRestController as REST API
 *
 * <p>Exposes REST endpoints for the CommandDefinition entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CommandDefinitionBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCommandDefinitionCommand</li>
 *      <li></li>UpdateCommandDefinitionCommand</li>
 *      <liDeleteCommandDefinitionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/CommandDefinition")
public class CommandDefinitionRestController extends BaseSpringRestController {

    /**
     * Handles create a CommandDefinition.  if not key provided, calls create, otherwise calls save
     * @param		CommandDefinition	commandDefinition
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateCommandDefinitionCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = CommandDefinitionService.getCommandDefinitionInstance().createCommandDefinition( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a CommandDefinition.  if no key provided, calls create, otherwise calls save
     * @param		CommandDefinition commandDefinition
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateCommandDefinitionCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateCommandDefinitionCommand
			// -----------------------------------------------
			completableFuture = CommandDefinitionService.getCommandDefinitionInstance().updateCommandDefinition(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "CommandDefinitionController:update() - successfully update CommandDefinition - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a CommandDefinition entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteCommandDefinitionCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	CommandDefinitionService delegate = CommandDefinitionService.getCommandDefinitionInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted CommandDefinition with key " + command.getCommandDefinitionId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a CommandDefinition using a UUID
     * @param		UUID uuid 
     * @return		CommandDefinition
     */    
    @GetMapping("/load")
    public CommandDefinition load( @RequestParam(required=true) UUID uuid ) {    	
    	CommandDefinition entity = null;

    	try {  
    		entity = CommandDefinitionService.getCommandDefinitionInstance().getCommandDefinition( new CommandDefinitionFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load CommandDefinition using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all CommandDefinition business objects
     * @return		Set<CommandDefinition>
     */
    @GetMapping("/")
    public List<CommandDefinition> loadAll() {                
    	List<CommandDefinition> commandDefinitionList = null;
        
    	try {
            // load the CommandDefinition
            commandDefinitionList = CommandDefinitionService.getCommandDefinitionInstance().getAllCommandDefinition();
            
            if ( commandDefinitionList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all CommandDefinitions" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all CommandDefinitions ", exc );
        	return null;
        }

        return commandDefinitionList;
                            
    }

    /**
     * save DeviceModel on CommandDefinition
     * @param		command AssignDeviceModelToCommandDefinitionCommand
     */     
	@PutMapping("/assignDeviceModel")
	public void assignDeviceModel( @RequestBody AssignDeviceModelToCommandDefinitionCommand command ) {
		try {
			CommandDefinitionService.getCommandDefinitionInstance().assignDeviceModel( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign DeviceModel", exc );
        }
	}

    /**
     * unassign DeviceModel on CommandDefinition
     * @param		 command UnAssignDeviceModelFromCommandDefinitionCommand
     */     
	@PutMapping("/unAssignDeviceModel")
	public void unAssignDeviceModel( @RequestBody(required=true)  UnAssignDeviceModelFromCommandDefinitionCommand command ) {
		try {
			CommandDefinitionService.getCommandDefinitionInstance().unAssignDeviceModel( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign DeviceModel", exc );
		}
	}
	

    /**
     * save Actuators on CommandDefinition
     * @param		command AssignActuatorsToCommandDefinitionCommand
     */     
	@PutMapping("/addToActuators")
	public void addToActuators( @RequestBody(required=true) AssignActuatorsToCommandDefinitionCommand command ) {
		try {
			CommandDefinitionService.getCommandDefinitionInstance().addToActuators( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Actuators", exc );
		}
	}

    /**
     * remove Actuators on CommandDefinition
     * @param		command RemoveActuatorsFromCommandDefinitionCommand
     */     	
	@PutMapping("/removeFromActuators")
	public void removeFromActuators( 	@RequestBody(required=true) RemoveActuatorsFromCommandDefinitionCommand command )
	{		
		try {
			CommandDefinitionService.getCommandDefinitionInstance().removeFromActuators( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Actuators", exc );
		}
	}

    /**
     * save CommandInvocations on CommandDefinition
     * @param		command AssignCommandInvocationsToCommandDefinitionCommand
     */     
	@PutMapping("/addToCommandInvocations")
	public void addToCommandInvocations( @RequestBody(required=true) AssignCommandInvocationsToCommandDefinitionCommand command ) {
		try {
			CommandDefinitionService.getCommandDefinitionInstance().addToCommandInvocations( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set CommandInvocations", exc );
		}
	}

    /**
     * remove CommandInvocations on CommandDefinition
     * @param		command RemoveCommandInvocationsFromCommandDefinitionCommand
     */     	
	@PutMapping("/removeFromCommandInvocations")
	public void removeFromCommandInvocations( 	@RequestBody(required=true) RemoveCommandInvocationsFromCommandDefinitionCommand command )
	{		
		try {
			CommandDefinitionService.getCommandDefinitionInstance().removeFromCommandInvocations( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set CommandInvocations", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected CommandDefinition commandDefinition = null;
    private static final Logger LOGGER = Logger.getLogger(CommandDefinitionRestController.class.getName());
    
}
