/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * DeviceModelRestController as REST API
 *
 * <p>Exposes REST endpoints for the DeviceModel entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DeviceModelBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDeviceModelCommand</li>
 *      <li></li>UpdateDeviceModelCommand</li>
 *      <liDeleteDeviceModelCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/DeviceModel")
public class DeviceModelRestController extends BaseSpringRestController {

    /**
     * Handles create a DeviceModel.  if not key provided, calls create, otherwise calls save
     * @param		DeviceModel	deviceModel
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateDeviceModelCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = DeviceModelService.getDeviceModelInstance().createDeviceModel( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a DeviceModel.  if no key provided, calls create, otherwise calls save
     * @param		DeviceModel deviceModel
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateDeviceModelCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateDeviceModelCommand
			// -----------------------------------------------
			completableFuture = DeviceModelService.getDeviceModelInstance().updateDeviceModel(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "DeviceModelController:update() - successfully update DeviceModel - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a DeviceModel entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteDeviceModelCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	DeviceModelService delegate = DeviceModelService.getDeviceModelInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted DeviceModel with key " + command.getDeviceModelId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a DeviceModel using a UUID
     * @param		UUID uuid 
     * @return		DeviceModel
     */    
    @GetMapping("/load")
    public DeviceModel load( @RequestParam(required=true) UUID uuid ) {    	
    	DeviceModel entity = null;

    	try {  
    		entity = DeviceModelService.getDeviceModelInstance().getDeviceModel( new DeviceModelFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load DeviceModel using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all DeviceModel business objects
     * @return		Set<DeviceModel>
     */
    @GetMapping("/")
    public List<DeviceModel> loadAll() {                
    	List<DeviceModel> deviceModelList = null;
        
    	try {
            // load the DeviceModel
            deviceModelList = DeviceModelService.getDeviceModelInstance().getAllDeviceModel();
            
            if ( deviceModelList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all DeviceModels" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all DeviceModels ", exc );
        	return null;
        }

        return deviceModelList;
                            
    }

    /**
     * save Vendor on DeviceModel
     * @param		command AssignVendorToDeviceModelCommand
     */     
	@PutMapping("/assignVendor")
	public void assignVendor( @RequestBody AssignVendorToDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().assignVendor( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Vendor", exc );
        }
	}

    /**
     * unassign Vendor on DeviceModel
     * @param		 command UnAssignVendorFromDeviceModelCommand
     */     
	@PutMapping("/unAssignVendor")
	public void unAssignVendor( @RequestBody(required=true)  UnAssignVendorFromDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().unAssignVendor( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Vendor", exc );
		}
	}
	
    /**
     * save TwinTemplate on DeviceModel
     * @param		command AssignTwinTemplateToDeviceModelCommand
     */     
	@PutMapping("/assignTwinTemplate")
	public void assignTwinTemplate( @RequestBody AssignTwinTemplateToDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().assignTwinTemplate( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign TwinTemplate", exc );
        }
	}

    /**
     * unassign TwinTemplate on DeviceModel
     * @param		 command UnAssignTwinTemplateFromDeviceModelCommand
     */     
	@PutMapping("/unAssignTwinTemplate")
	public void unAssignTwinTemplate( @RequestBody(required=true)  UnAssignTwinTemplateFromDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().unAssignTwinTemplate( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign TwinTemplate", exc );
		}
	}
	

    /**
     * save HardwareModules on DeviceModel
     * @param		command AssignHardwareModulesToDeviceModelCommand
     */     
	@PutMapping("/addToHardwareModules")
	public void addToHardwareModules( @RequestBody(required=true) AssignHardwareModulesToDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().addToHardwareModules( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set HardwareModules", exc );
		}
	}

    /**
     * remove HardwareModules on DeviceModel
     * @param		command RemoveHardwareModulesFromDeviceModelCommand
     */     	
	@PutMapping("/removeFromHardwareModules")
	public void removeFromHardwareModules( 	@RequestBody(required=true) RemoveHardwareModulesFromDeviceModelCommand command )
	{		
		try {
			DeviceModelService.getDeviceModelInstance().removeFromHardwareModules( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set HardwareModules", exc );
		}
	}

    /**
     * save FirmwareReleases on DeviceModel
     * @param		command AssignFirmwareReleasesToDeviceModelCommand
     */     
	@PutMapping("/addToFirmwareReleases")
	public void addToFirmwareReleases( @RequestBody(required=true) AssignFirmwareReleasesToDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().addToFirmwareReleases( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set FirmwareReleases", exc );
		}
	}

    /**
     * remove FirmwareReleases on DeviceModel
     * @param		command RemoveFirmwareReleasesFromDeviceModelCommand
     */     	
	@PutMapping("/removeFromFirmwareReleases")
	public void removeFromFirmwareReleases( 	@RequestBody(required=true) RemoveFirmwareReleasesFromDeviceModelCommand command )
	{		
		try {
			DeviceModelService.getDeviceModelInstance().removeFromFirmwareReleases( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set FirmwareReleases", exc );
		}
	}

    /**
     * save CommandDefinitions on DeviceModel
     * @param		command AssignCommandDefinitionsToDeviceModelCommand
     */     
	@PutMapping("/addToCommandDefinitions")
	public void addToCommandDefinitions( @RequestBody(required=true) AssignCommandDefinitionsToDeviceModelCommand command ) {
		try {
			DeviceModelService.getDeviceModelInstance().addToCommandDefinitions( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set CommandDefinitions", exc );
		}
	}

    /**
     * remove CommandDefinitions on DeviceModel
     * @param		command RemoveCommandDefinitionsFromDeviceModelCommand
     */     	
	@PutMapping("/removeFromCommandDefinitions")
	public void removeFromCommandDefinitions( 	@RequestBody(required=true) RemoveCommandDefinitionsFromDeviceModelCommand command )
	{		
		try {
			DeviceModelService.getDeviceModelInstance().removeFromCommandDefinitions( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set CommandDefinitions", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected DeviceModel deviceModel = null;
    private static final Logger LOGGER = Logger.getLogger(DeviceModelRestController.class.getName());
    
}
