/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * NetworkProfileRestController as REST API
 *
 * <p>Exposes REST endpoints for the NetworkProfile entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	NetworkProfileBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateNetworkProfileCommand</li>
 *      <li></li>UpdateNetworkProfileCommand</li>
 *      <liDeleteNetworkProfileCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/NetworkProfile")
public class NetworkProfileRestController extends BaseSpringRestController {

    /**
     * Handles create a NetworkProfile.  if not key provided, calls create, otherwise calls save
     * @param		NetworkProfile	networkProfile
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateNetworkProfileCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = NetworkProfileService.getNetworkProfileInstance().createNetworkProfile( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a NetworkProfile.  if no key provided, calls create, otherwise calls save
     * @param		NetworkProfile networkProfile
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateNetworkProfileCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateNetworkProfileCommand
			// -----------------------------------------------
			completableFuture = NetworkProfileService.getNetworkProfileInstance().updateNetworkProfile(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "NetworkProfileController:update() - successfully update NetworkProfile - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a NetworkProfile entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteNetworkProfileCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	NetworkProfileService delegate = NetworkProfileService.getNetworkProfileInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted NetworkProfile with key " + command.getNetworkProfileId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a NetworkProfile using a UUID
     * @param		UUID uuid 
     * @return		NetworkProfile
     */    
    @GetMapping("/load")
    public NetworkProfile load( @RequestParam(required=true) UUID uuid ) {    	
    	NetworkProfile entity = null;

    	try {  
    		entity = NetworkProfileService.getNetworkProfileInstance().getNetworkProfile( new NetworkProfileFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load NetworkProfile using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all NetworkProfile business objects
     * @return		Set<NetworkProfile>
     */
    @GetMapping("/")
    public List<NetworkProfile> loadAll() {                
    	List<NetworkProfile> networkProfileList = null;
        
    	try {
            // load the NetworkProfile
            networkProfileList = NetworkProfileService.getNetworkProfileInstance().getAllNetworkProfile();
            
            if ( networkProfileList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all NetworkProfiles" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all NetworkProfiles ", exc );
        	return null;
        }

        return networkProfileList;
                            
    }

    /**
     * save Device on NetworkProfile
     * @param		command AssignDeviceToNetworkProfileCommand
     */     
	@PutMapping("/assignDevice")
	public void assignDevice( @RequestBody AssignDeviceToNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().assignDevice( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Device", exc );
        }
	}

    /**
     * unassign Device on NetworkProfile
     * @param		 command UnAssignDeviceFromNetworkProfileCommand
     */     
	@PutMapping("/unAssignDevice")
	public void unAssignDevice( @RequestBody(required=true)  UnAssignDeviceFromNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().unAssignDevice( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Device", exc );
		}
	}
	
    /**
     * save Gateway on NetworkProfile
     * @param		command AssignGatewayToNetworkProfileCommand
     */     
	@PutMapping("/assignGateway")
	public void assignGateway( @RequestBody AssignGatewayToNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().assignGateway( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Gateway", exc );
        }
	}

    /**
     * unassign Gateway on NetworkProfile
     * @param		 command UnAssignGatewayFromNetworkProfileCommand
     */     
	@PutMapping("/unAssignGateway")
	public void unAssignGateway( @RequestBody(required=true)  UnAssignGatewayFromNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().unAssignGateway( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Gateway", exc );
		}
	}
	
    /**
     * save SimCard on NetworkProfile
     * @param		command AssignSimCardToNetworkProfileCommand
     */     
	@PutMapping("/assignSimCard")
	public void assignSimCard( @RequestBody AssignSimCardToNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().assignSimCard( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign SimCard", exc );
        }
	}

    /**
     * unassign SimCard on NetworkProfile
     * @param		 command UnAssignSimCardFromNetworkProfileCommand
     */     
	@PutMapping("/unAssignSimCard")
	public void unAssignSimCard( @RequestBody(required=true)  UnAssignSimCardFromNetworkProfileCommand command ) {
		try {
			NetworkProfileService.getNetworkProfileInstance().unAssignSimCard( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign SimCard", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected NetworkProfile networkProfile = null;
    private static final Logger LOGGER = Logger.getLogger(NetworkProfileRestController.class.getName());
    
}
