/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TenantRestController as REST API
 *
 * <p>Exposes REST endpoints for the Tenant entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TenantBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTenantCommand</li>
 *      <li></li>UpdateTenantCommand</li>
 *      <liDeleteTenantCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Tenant")
public class TenantRestController extends BaseSpringRestController {

    /**
     * Handles create a Tenant.  if not key provided, calls create, otherwise calls save
     * @param		Tenant	tenant
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateTenantCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = TenantService.getTenantInstance().createTenant( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Tenant.  if no key provided, calls create, otherwise calls save
     * @param		Tenant tenant
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateTenantCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateTenantCommand
			// -----------------------------------------------
			completableFuture = TenantService.getTenantInstance().updateTenant(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "TenantController:update() - successfully update Tenant - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Tenant entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteTenantCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	TenantService delegate = TenantService.getTenantInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Tenant with key " + command.getTenantId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Tenant using a UUID
     * @param		UUID uuid 
     * @return		Tenant
     */    
    @GetMapping("/load")
    public Tenant load( @RequestParam(required=true) UUID uuid ) {    	
    	Tenant entity = null;

    	try {  
    		entity = TenantService.getTenantInstance().getTenant( new TenantFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Tenant using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Tenant business objects
     * @return		Set<Tenant>
     */
    @GetMapping("/")
    public List<Tenant> loadAll() {                
    	List<Tenant> tenantList = null;
        
    	try {
            // load the Tenant
            tenantList = TenantService.getTenantInstance().getAllTenant();
            
            if ( tenantList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Tenants" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Tenants ", exc );
        	return null;
        }

        return tenantList;
                            
    }


    /**
     * save Sites on Tenant
     * @param		command AssignSitesToTenantCommand
     */     
	@PutMapping("/addToSites")
	public void addToSites( @RequestBody(required=true) AssignSitesToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToSites( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Sites", exc );
		}
	}

    /**
     * remove Sites on Tenant
     * @param		command RemoveSitesFromTenantCommand
     */     	
	@PutMapping("/removeFromSites")
	public void removeFromSites( 	@RequestBody(required=true) RemoveSitesFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromSites( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Sites", exc );
		}
	}

    /**
     * save Users on Tenant
     * @param		command AssignUsersToTenantCommand
     */     
	@PutMapping("/addToUsers")
	public void addToUsers( @RequestBody(required=true) AssignUsersToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToUsers( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Users", exc );
		}
	}

    /**
     * remove Users on Tenant
     * @param		command RemoveUsersFromTenantCommand
     */     	
	@PutMapping("/removeFromUsers")
	public void removeFromUsers( 	@RequestBody(required=true) RemoveUsersFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromUsers( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Users", exc );
		}
	}

    /**
     * save Devices on Tenant
     * @param		command AssignDevicesToTenantCommand
     */     
	@PutMapping("/addToDevices")
	public void addToDevices( @RequestBody(required=true) AssignDevicesToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToDevices( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Devices", exc );
		}
	}

    /**
     * remove Devices on Tenant
     * @param		command RemoveDevicesFromTenantCommand
     */     	
	@PutMapping("/removeFromDevices")
	public void removeFromDevices( 	@RequestBody(required=true) RemoveDevicesFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromDevices( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Devices", exc );
		}
	}

    /**
     * save DataRetentionPolicies on Tenant
     * @param		command AssignDataRetentionPoliciesToTenantCommand
     */     
	@PutMapping("/addToDataRetentionPolicies")
	public void addToDataRetentionPolicies( @RequestBody(required=true) AssignDataRetentionPoliciesToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToDataRetentionPolicies( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set DataRetentionPolicies", exc );
		}
	}

    /**
     * remove DataRetentionPolicies on Tenant
     * @param		command RemoveDataRetentionPoliciesFromTenantCommand
     */     	
	@PutMapping("/removeFromDataRetentionPolicies")
	public void removeFromDataRetentionPolicies( 	@RequestBody(required=true) RemoveDataRetentionPoliciesFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromDataRetentionPolicies( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set DataRetentionPolicies", exc );
		}
	}

    /**
     * save ConnectivityPlans on Tenant
     * @param		command AssignConnectivityPlansToTenantCommand
     */     
	@PutMapping("/addToConnectivityPlans")
	public void addToConnectivityPlans( @RequestBody(required=true) AssignConnectivityPlansToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToConnectivityPlans( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ConnectivityPlans", exc );
		}
	}

    /**
     * remove ConnectivityPlans on Tenant
     * @param		command RemoveConnectivityPlansFromTenantCommand
     */     	
	@PutMapping("/removeFromConnectivityPlans")
	public void removeFromConnectivityPlans( 	@RequestBody(required=true) RemoveConnectivityPlansFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromConnectivityPlans( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ConnectivityPlans", exc );
		}
	}

    /**
     * save SimCards on Tenant
     * @param		command AssignSimCardsToTenantCommand
     */     
	@PutMapping("/addToSimCards")
	public void addToSimCards( @RequestBody(required=true) AssignSimCardsToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToSimCards( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set SimCards", exc );
		}
	}

    /**
     * remove SimCards on Tenant
     * @param		command RemoveSimCardsFromTenantCommand
     */     	
	@PutMapping("/removeFromSimCards")
	public void removeFromSimCards( 	@RequestBody(required=true) RemoveSimCardsFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromSimCards( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set SimCards", exc );
		}
	}

    /**
     * save MessagingEndpoints on Tenant
     * @param		command AssignMessagingEndpointsToTenantCommand
     */     
	@PutMapping("/addToMessagingEndpoints")
	public void addToMessagingEndpoints( @RequestBody(required=true) AssignMessagingEndpointsToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToMessagingEndpoints( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set MessagingEndpoints", exc );
		}
	}

    /**
     * remove MessagingEndpoints on Tenant
     * @param		command RemoveMessagingEndpointsFromTenantCommand
     */     	
	@PutMapping("/removeFromMessagingEndpoints")
	public void removeFromMessagingEndpoints( 	@RequestBody(required=true) RemoveMessagingEndpointsFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromMessagingEndpoints( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set MessagingEndpoints", exc );
		}
	}

    /**
     * save AccessPolicies on Tenant
     * @param		command AssignAccessPoliciesToTenantCommand
     */     
	@PutMapping("/addToAccessPolicies")
	public void addToAccessPolicies( @RequestBody(required=true) AssignAccessPoliciesToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToAccessPolicies( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set AccessPolicies", exc );
		}
	}

    /**
     * remove AccessPolicies on Tenant
     * @param		command RemoveAccessPoliciesFromTenantCommand
     */     	
	@PutMapping("/removeFromAccessPolicies")
	public void removeFromAccessPolicies( 	@RequestBody(required=true) RemoveAccessPoliciesFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromAccessPolicies( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set AccessPolicies", exc );
		}
	}

    /**
     * save DeviceGroups on Tenant
     * @param		command AssignDeviceGroupsToTenantCommand
     */     
	@PutMapping("/addToDeviceGroups")
	public void addToDeviceGroups( @RequestBody(required=true) AssignDeviceGroupsToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToDeviceGroups( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set DeviceGroups", exc );
		}
	}

    /**
     * remove DeviceGroups on Tenant
     * @param		command RemoveDeviceGroupsFromTenantCommand
     */     	
	@PutMapping("/removeFromDeviceGroups")
	public void removeFromDeviceGroups( 	@RequestBody(required=true) RemoveDeviceGroupsFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromDeviceGroups( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set DeviceGroups", exc );
		}
	}

    /**
     * save AlertRules on Tenant
     * @param		command AssignAlertRulesToTenantCommand
     */     
	@PutMapping("/addToAlertRules")
	public void addToAlertRules( @RequestBody(required=true) AssignAlertRulesToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToAlertRules( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set AlertRules", exc );
		}
	}

    /**
     * remove AlertRules on Tenant
     * @param		command RemoveAlertRulesFromTenantCommand
     */     	
	@PutMapping("/removeFromAlertRules")
	public void removeFromAlertRules( 	@RequestBody(required=true) RemoveAlertRulesFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromAlertRules( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set AlertRules", exc );
		}
	}

    /**
     * save MaintenanceTickets on Tenant
     * @param		command AssignMaintenanceTicketsToTenantCommand
     */     
	@PutMapping("/addToMaintenanceTickets")
	public void addToMaintenanceTickets( @RequestBody(required=true) AssignMaintenanceTicketsToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToMaintenanceTickets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set MaintenanceTickets", exc );
		}
	}

    /**
     * remove MaintenanceTickets on Tenant
     * @param		command RemoveMaintenanceTicketsFromTenantCommand
     */     	
	@PutMapping("/removeFromMaintenanceTickets")
	public void removeFromMaintenanceTickets( 	@RequestBody(required=true) RemoveMaintenanceTicketsFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromMaintenanceTickets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set MaintenanceTickets", exc );
		}
	}

    /**
     * save UsageRecords on Tenant
     * @param		command AssignUsageRecordsToTenantCommand
     */     
	@PutMapping("/addToUsageRecords")
	public void addToUsageRecords( @RequestBody(required=true) AssignUsageRecordsToTenantCommand command ) {
		try {
			TenantService.getTenantInstance().addToUsageRecords( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set UsageRecords", exc );
		}
	}

    /**
     * remove UsageRecords on Tenant
     * @param		command RemoveUsageRecordsFromTenantCommand
     */     	
	@PutMapping("/removeFromUsageRecords")
	public void removeFromUsageRecords( 	@RequestBody(required=true) RemoveUsageRecordsFromTenantCommand command )
	{		
		try {
			TenantService.getTenantInstance().removeFromUsageRecords( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set UsageRecords", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Tenant tenant = null;
    private static final Logger LOGGER = Logger.getLogger(TenantRestController.class.getName());
    
}
